First working awk

diff --git a/tradelog b/tradelog
--- a/tradelog
+++ b/tradelog
@@ -6,7 +6,7 @@ COMMAND=""		# Store arguments commands
 LOG_FILES=""		# Input file in .log format
 GZ_LOG_FILES="" 	# Input file in .gz archiv
 READ_INPUT=""		# Here i ll store input logs 
-READ_FILTERED=""	#
+FILTER=""		# I ll change READ_INPUT using filter	
 IS_T_COM_OR_FIL="0"	# Is there command or filter indicator
 BEFORE_TIME=""		# write only logs before this time 
 AFTER_TIME="9999-99-99" # WRITE only logs afther this time 
@@ -188,7 +188,7 @@ store_input()
 	# IF THERE ARE NO PARRAMETERS i ll store stdin
 	if [ -z "$COMMAND" ] && [ -z "$LOG_FILES" ] && [ -z "$GZ_LOG_FILES" ]; then
 		if [ $IS_T_COM_OR_FIL -eq "1" ]; then
-			echo "If there is input from stdin u cant add commands or filters." >&2 
+			echo "ERROR You have to specify ticker ater -t or If there is input from stdin u cant add commands or filters." >&2 
 		else
 			READ_INPUT="${1:-/dev/stdin}"
 			READ_INPUT=$(cat "$READ_INPUT") 
@@ -212,7 +212,7 @@ debug_tempo()
 	echo "l_f>     $LOG_FILES"
 	echo "aft:     $AFTER_TIME"
 	echo "bft:     $BEFORE_TIME"
-	echo "width:   $BEFORE_TIME"
+	echo "width:   $WIDTH"
 	echo "thick:   $THICK"
 }
 
@@ -221,20 +221,15 @@ argument_parser "$@" 		# Parse arguments and store them.
 
 bad_argument_error	# If program has bad arguments it ll exit with error
 store_input		# Store inputs to READ_INPUT 
-
-TICK_FILTER=""
-#READ_FILTERED="eval $READ_INPUT | awk -F ';' 'if (\$1 > $AFTER_TIME && {print \$0}'"
-
+FILTER="$READ_INPUT | awk final_arg -F ';' '{print \$0}'"
+READ_INPUT="$FILTER"
 
 echo "$READ_INPUT"
-echo "$READ_INPUT"
-
 debug_tempo 		# Giv debug information. 
 
-if [ ]; then
-	eval "$READ_FILRET_VSTUP | "
-fi
 
+
+#READ_FILTERED="eval $READ_INPUT | awk -F ';' 'if (\$1 > $AFTER_TIME && {print \$0}'"
 
 
 
